# Generated by Django 4.1.7 on 2023-03-18 02:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(null=True)),
                ('customer_name', models.CharField(max_length=150, null=True)),
                ('product', models.IntegerField(null=True)),
                ('product_name', models.CharField(max_length=150, null=True)),
                ('delivery_time', models.DateTimeField(null=True)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('house_number', models.CharField(max_length=150)),
                ('payment_method', models.CharField(max_length=150, null=True)),
            ],
            options={
                'ordering': ['delivery_time'],
            },
        ),
        migrations.CreateModel(
            name='AveragePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(null=True)),
                ('customer_name', models.CharField(max_length=150, null=True)),
                ('product', models.IntegerField(null=True)),
                ('product_name', models.CharField(max_length=150, null=True)),
                ('price', models.IntegerField(null=True)),
                ('size', models.CharField(max_length=15, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('number', models.IntegerField(null=True)),
                ('summ', models.IntegerField(null=True)),
                ('added_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-added_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(editable=False, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(unique=True)),
                ('number', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=15, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(null=True)),
                ('customer_name', models.CharField(max_length=150, null=True)),
                ('product', models.IntegerField(null=True)),
                ('product_name', models.CharField(max_length=150, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(editable=False, max_length=150)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField(null=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image (width and height should be equal)')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DFDraft', 'Draft'), ('PBPublished', 'Published')], default='DFDraft', max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.color')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.size')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('star', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.product')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
