# Generated by Django 4.1.7 on 2023-03-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='customer',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
