# Generated by Django 4.1.7 on 2023-03-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_filter_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AveragePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_time']},
        ),
    ]
