# Generated by Django 4.1.7 on 2023-03-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_averageprice_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('number', models.IntegerField()),
                ('added_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-added_time'],
            },
        ),
    ]
