# Generated by Django 4.1.7 on 2023-03-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
