# Generated by Django 4.1.7 on 2023-03-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_filter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
