# Generated by Django 4.1.7 on 2023-03-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
