# Generated by Django 4.1.7 on 2023-03-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_cart_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
