# Generated by Django 4.1.7 on 2023-03-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_rename_product_cart_product_name_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
    ]
