# Generated by Django 4.1.7 on 2023-03-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_product_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_name',
            new_name='product',
        ),
    ]
