# Generated by Django 4.1.7 on 2023-03-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_rename_product_name_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='summ',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
