# Generated by Django 4.1.7 on 2023-03-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_cart_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image (width and height should be equal)'),
        ),
    ]
