# Generated by Django 4.1.7 on 2023-03-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_purchased_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='activated',
            name='payment_method',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
