# Generated by Django 4.1.7 on 2023-03-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_activated_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activated',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
