# Generated by Django 4.1.7 on 2023-03-15 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_activated_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchased',
            options={'ordering': ['-product__delivery_time']},
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='purchased_time',
        ),
        migrations.AlterField(
            model_name='activated',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.product'),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.activated'),
        ),
    ]
