# Generated by Django 4.1.7 on 2023-03-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='summ',
            field=models.IntegerField(null=True),
        ),
    ]
