# Generated by Django 4.1.7 on 2023-03-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activated',
            name='customer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activated',
            name='product',
            field=models.IntegerField(null=True),
        ),
    ]
