# Generated by Django 4.1.7 on 2023-03-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_alter_activated_customer_alter_activated_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchased',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='purchased',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchased',
            name='customer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='product',
            field=models.IntegerField(null=True),
        ),
    ]
