# Generated by Django 4.1.7 on 2023-03-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_alter_purchased_options_purchased_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activated',
            name='product_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='purchased',
            name='product_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
