# Generated by Django 4.1.7 on 2023-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_activated_product_name_cart_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activated',
            name='customer_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='purchased',
            name='customer_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
